"""2-17-21 try3

Revision ID: c451a0f283da
Revises: dc57c2203e0a
Create Date: 2021-02-17 10:22:23.487074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c451a0f283da'
down_revision = 'dc57c2203e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('car_user_id_fkey', 'car', type_='foreignkey')
    op.create_foreign_key(None, 'car', 'user', ['user_id'], ['token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car', type_='foreignkey')
    op.create_foreign_key('car_user_id_fkey', 'car', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
